"""initial

Revision ID: 9a400be00456
Revises:
Create Date: 2026-07-25 18:42:39.599967

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a400be00456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('shopify_domain', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('return_policy_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('reason_code', sa.Enum('ITEM_NOT_RECEIVED', 'ITEM_DEFECTIVE', 'INCORRECT_AMOUNT', 'UNAUTHORIZED_TRANSACTION', 'SUBSCRIPTION_CANCELLED', name='disputereasoncode'), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'EVIDENCE_GATHERING', 'UNDER_REVIEW', 'DECISION_RENDERED', 'CLOSED', name='disputestatus'), nullable=True),
    sa.Column('user_narrative', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Enum('REFUND_USER', 'REJECT_CLAIM', 'PARTIAL_REFUND', 'NEEDS_HUMAN_INTERVENTION', name='verdicttype'), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('verdict_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('action_taken', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_fetched_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shopify_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shiprocket_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispute_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.Enum('USER', 'MERCHANT', 'AUTO_API', name='evidencesource'), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('ocr_extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_vision_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('auto_fetched_logs')
    op.drop_table('audit_trail')
    op.drop_table('disputes')
    op.drop_table('users')
    op.drop_table('merchants')
    # ### end Alembic commands ###
