"""add merchant_id to users

Revision ID: ab7f29bdbd2a
Revises: 9a400be00456
Create Date: 2026-07-26 00:03:23.303222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7f29bdbd2a'
down_revision: Union[str, None] = '9a400be00456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('merchant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'merchants', ['merchant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'merchant_id')
    # ### end Alembic commands ###
